publishDir=""
baseurl                 = "mariaoliveira2407.github.io/"               # Your domain name. Must end with "/"
languageCode            = "pt-br"
title                   = "Maria Tereza N. Oliveira"
theme = "hugo-theme-sam"
pygmentsStyle           = "manni"                     # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# googleAnalytics       = "xxx"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/sam.ico"
    homepage            = "main"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = "A vida é desafio."

# Metadata
    description         = "A new Hugo site."            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/tn.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/about"
    text = "Maria Tereza N. Oliveira"

[[params.mainMenu]]
    link = "/formação"
    text = "Experiência acadêmica"
    
[[params.mainMenu]]
    link = "/posts"
    text = "Experiência profissional"

[[params.mainMenu]]
    link = "/gallery"
    text = "Contato"


    
